name = input("Enter your name: ")
age = int(input("Enter your age: "))
dob = input("Enter your Date of birth: ")
gender = input("Enter your Gender: ")
phone = int(input("Enter your Phone number: "))
email = input("Enter your Email: ")
address = input("Enter your Address: ")
education = input("Enter your Education Qualification: ")
work = input("Enter your work Experience: ")

print(" Name is : ", name)
print(" Age is : ", age) 
print(" Date of Birth is : ", dob)
print(" Gender is : ", gender)
print(" Phone number is : ", phone)
print(" Email ID is : ", email)
print(" Address is : ", address)
print(" Education Qualification is : ", education)
print(" Work Experience is : ", work)